<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="lowcoders" nsURI="http://lev4rec/lowcode" nsPrefix="lowcoders">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dataset" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="indipendentVariables" upperBound="-1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataStructure" eType="#//DataStructure"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preprocessing" upperBound="-1"
        eType="#//PreprocessingTechnique"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datasetManipulationLibrary"
        upperBound="-1" eType="#//DatasetManipulationLibrary"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RSModel" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataset" eType="#//Dataset"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="presentationLayer" eType="#//PresentationLayer"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="evaluation" eType="#//Evaluation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recommendationSystem" lowerBound="1"
        eType="#//RecommendationSystem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSource" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PresentationLayer" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="recommendations" eType="#//RecommendedItem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WebInterface" eSuperTypes="#//PresentationLayer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="library" eType="#//WebInterfaceLibrary"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WebApplication" eSuperTypes="#//NamedElement #//PresentationLayer"/>
  <eClassifiers xsi:type="ecore:EClass" name="IDEIntegration" eSuperTypes="#//PresentationLayer"/>
  <eClassifiers xsi:type="ecore:EClass" name="TraversableGraph" eSuperTypes="#//PresentationLayer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Evaluation" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baselines" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metrics" upperBound="-1"
        eType="#//Metric"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validationtechnique" upperBound="-1"
        eType="#//ValidationTechnique" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidationTechnique" abstract="true"
      eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nOfRecommendations" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CollaborativeFilteringAlgorithm">
    <eLiterals name="itemBased"/>
    <eLiterals name="userBased" value="1"/>
    <eLiterals name="contentBased" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WebContainer">
    <eLiterals name="tomcat"/>
    <eLiterals name="jetty" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Metric">
    <eLiterals name="PRECISION"/>
    <eLiterals name="RECALL" value="1"/>
    <eLiterals name="F1_MEASURE" value="2"/>
    <eLiterals name="CATALOG_COVERAGE" value="3"/>
    <eLiterals name="NOVELTY" value="4"/>
    <eLiterals name="SALE_DIVERSITY"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnsupervisedDataset" eSuperTypes="#//Dataset"/>
  <eClassifiers xsi:type="ecore:EClass" name="SupervisedDataset" eSuperTypes="#//Dataset">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependatVariable" lowerBound="1"
        eType="#//Variable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataSource" lowerBound="1"
        eType="#//DataSource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Preprocessing" eType="#//Preprocessing"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//VariableType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMissingValueAllowed"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMultiple" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Preprocessing">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preprocessigTechnique"
        upperBound="-1" eType="#//PreprocessingTechnique"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PreprocessingTechnique">
    <eLiterals name="DUPLICATES_REMOVAL" literal="DUPLICATES_REMOVAL"/>
    <eLiterals name="NLP" value="1"/>
    <eLiterals name="NORMALIZATION" value="2"/>
    <eLiterals name="MISSING_DATA_MANIPULATION" value="3"/>
    <eLiterals name="VECTORIZATION" value="4"/>
    <eLiterals name="FEATURE_SCALING" value="5"/>
    <eLiterals name="TFIDF" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeRepository" eSuperTypes="#//DataSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadata" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationChannel" eSuperTypes="#//DataSource"/>
  <eClassifiers xsi:type="ecore:EClass" name="BugTrackingSystem" eSuperTypes="#//DataSource"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataStructure" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Graph" eSuperTypes="#//DataStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" eType="#//VariableRelation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Matrix" eSuperTypes="#//DataStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tree" eSuperTypes="#//Graph"/>
  <eClassifiers xsi:type="ecore:EClass" name="TextualContent" eSuperTypes="#//DataStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rootPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ARFF" eSuperTypes="#//DataStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VariableType">
    <eLiterals name="String"/>
    <eLiterals name="Boolean" value="1"/>
    <eLiterals name="CategoricalData" value="2"/>
    <eLiterals name="Integer" value="3"/>
    <eLiterals name="Float" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecommendationSystem" abstract="true"
      eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="RecommenderSettings" upperBound="-1"
        eType="#//RecommendationSetting" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recommendationScope" eType="#//RecommendedItem"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recommendationContext"
        eType="#//RecommendationContext" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generator" eType="#//PyLibType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MachineLearningBasedRS" eSuperTypes="#//RecommendationSystem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numEpochs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="learningRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="miniBatchSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MemoryBasedRS_NOTSURE" eSuperTypes="#//RecommendationSystem"/>
  <eClassifiers xsi:type="ecore:EClass" name="FilteringRS" eSuperTypes="#//RecommendationSystem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filteringRSAlgorithm" eType="#//FilteringRSAlgorithm"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="similarityCalculator" eType="#//SimilarityFunction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cutoff" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="neighborhood" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataMiningRS" eSuperTypes="#//RecommendationSystem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataMiningRSAlgorithm"
        eType="#//DataMiningRSAlgorithm"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomRecommender_SOREC" eSuperTypes="#//RecommendationSystem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredTools" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecommendationSetting">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataMiningRSAlgorithm">
    <eLiterals name="CLUSTERING"/>
    <eLiterals name="FREQUENT_ITEM_SET" value="1"/>
    <eLiterals name="ASSOCIATION_RULE" value="2"/>
    <eLiterals name="EVENT_STREAM" value="3"/>
    <eLiterals name="TEXT_MINING" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FilteringRSAlgorithm">
    <eLiterals name="CONTENT_BASED"/>
    <eLiterals name="DEMOGRAPHIC" value="1"/>
    <eLiterals name="USER_BASED" value="2"/>
    <eLiterals name="ITEM_BASED" value="3"/>
    <eLiterals name="CONTEXT_AWARE" value="4"/>
    <eLiterals name="HYBRID" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneticAlgorithm" eSuperTypes="#//RecommendationSystem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fitnessFunction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="searchStrategy" eType="#//SearchStrategy"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mutationOperator" eType="#//MutationOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SearchStrategy">
    <eLiterals name="SIMULATED_ANNELING"/>
    <eLiterals name="HILL_CLIMBING" value="1" literal="HILL_CLIMBING"/>
    <eLiterals name="GRADIENT_DESCENT" value="2"/>
    <eLiterals name="EGGHOLDER_FUNCTION" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MutationOperation">
    <eLiterals name="FIT_BIT"/>
    <eLiterals name="CROSSOVER" value="1"/>
    <eLiterals name="SHRINK_MUTATION" value="2"/>
    <eLiterals name="REPACE_MUTATION" value="3"/>
    <eLiterals name="PARTIAL_HYPER_MUTATION" value="4"/>
    <eLiterals name="DUPLICATION" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserStudy" eSuperTypes="#//ValidationTechnique">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//UserStudyType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="analysis" eType="#//UserStudyAnalysis"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UserStudyType">
    <eLiterals name="FIELD_STUDIES"/>
    <eLiterals name="CONTROLLED_EXPERIMENT" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UserStudyAnalysis">
    <eLiterals name="QUALITATIVE"/>
    <eLiterals name="QUANTITATIVE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CrossValidation" eSuperTypes="#//AutomatedValidation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfFold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groundTruthExtractor" eType="#//GroundTruthExtraction"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecommendationContext" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Usercontext" eType="#//DataStructure"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isProactiveSystem" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependencyManager" eSuperTypes="#//DataSource"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SimilarityFunction">
    <eLiterals name="COSINE_SIMILARITY"/>
    <eLiterals name="JACCARD_DISTANCE" value="1"/>
    <eLiterals name="WORD_EMBEDDINGS" value="2"/>
    <eLiterals name="LEVENSHTEIN_DISTANCE" value="3"/>
    <eLiterals name="SVD" value="4"/>
    <eLiterals name="GRAPH_BASED" value="5"/>
    <eLiterals name="MSD" value="6" literal="MSD"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroundTruthExtraction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sizeGT" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="splittingRules" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetVariable" eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="File" eSuperTypes="#//DataSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourcePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encoding" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecommendedItem" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outcame" upperBound="-1"
        eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PyLibType">
    <eLiterals name="SKLEARN"/>
    <eLiterals name="SURPRISE" value="1"/>
    <eLiterals name="TENSOR_FLOW" value="2"/>
    <eLiterals name="PYTORCH" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SolverType">
    <eLiterals name="ADAM"/>
    <eLiterals name="LBFGS" value="1"/>
    <eLiterals name="SGD" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="KernelType">
    <eLiterals name="PRECOMPUTED"/>
    <eLiterals name="LINEAR" value="1"/>
    <eLiterals name="POLY" value="2"/>
    <eLiterals name="RBF" value="3"/>
    <eLiterals name="SIGMOID" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActivationType">
    <eLiterals name="RELU"/>
    <eLiterals name="SIGMOID" value="1"/>
    <eLiterals name="TANH" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextValidation" eSuperTypes="#//ValidationTechnique">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testContext" eType="#//RecommendationContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DatasetManipulationLibrary">
    <eLiterals name="PANDAS"/>
    <eLiterals name="NUMPY" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WebInterfaceLibrary">
    <eLiterals name="FLASK"/>
    <eLiterals name="SPRING" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RawOutcomes" eSuperTypes="#//PresentationLayer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="#//RawFormat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RawFormat">
    <eLiterals name="CSV"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RandomSplitting" eSuperTypes="#//AutomatedValidation"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ValidationLibrary">
    <eLiterals name="SKLEARN"/>
    <eLiterals name="SURPRISE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutomatedValidation" eSuperTypes="#//ValidationTechnique">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="library" eType="#//ValidationLibrary"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeepNN" eSuperTypes="#//MachineLearningBasedRS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numHiddenLayer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConvolutionalNN" eSuperTypes="#//MachineLearningBasedRS"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bayesian" eSuperTypes="#//MachineLearningBasedRS"/>
  <eClassifiers xsi:type="ecore:EClass" name="RecurrentNN" eSuperTypes="#//MachineLearningBasedRS"/>
  <eClassifiers xsi:type="ecore:EClass" name="SVM" eSuperTypes="#//MachineLearningBasedRS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kernel" eType="#//KernelType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecisionTree" eSuperTypes="#//MachineLearningBasedRS"/>
  <eClassifiers xsi:type="ecore:EClass" name="FeedForwardNN" eSuperTypes="#//MachineLearningBasedRS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="solver" eType="#//SolverType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alpha" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activationFunction" eType="#//ActivationType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="randomState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
